global:
  # Interval default untuk scraping target
  scrape_interval: 15s 

scrape_configs:
  # Job untuk Prometheus (monitoring health-check internal)
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Job untuk ML Model Exporter
  - job_name: 'ml_model_exporter'
    static_configs:
      - targets: ['ml-model-service:8000']