name: Model Retraining CI

on:
  push:
    branches: [main]

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          pip install mlflow==2.19.0 dagshub pandas scikit-learn

      - name: Run mlflow project
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/Sabrinayusrina03/eksperimen_SML_SabrinaYusrina.mlflow
          MLFLOW_TRACKING_USERNAME: Sabrinayusrina03
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run ./MLProject --env-manager local --experiment-name "CI_Workflow_Run"

      - name: Get latest MLflow run_id
        run: |
          RUN_ID=$(mlflow runs list --experiment-name "CI_Workflow_Run" --max-results 1 --output csv | tail -n 1 | cut -d, -f1)
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "Latest Run ID is $RUN_ID"
      
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      
      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/mlruns/**/artifacts/model/model.pkl

      - name: Build Docker Model
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/laptop-price-model:latest \--build-arg DAGSHUB_TOKEN=${{ secrets.DAGSHUB_TOKEN }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/laptop-price-model:latest ${{ secrets.DOCKER_USERNAME }}/laptop-price-model:v1.0

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/laptop-price-model:latest
