name: Model Retraining CI

on:
  push:
    branches:
      - main

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies for MLflow Run
        run: |
          pip install mlflow dagshub

      - name: Set MLflow Tracking Credentials
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/Sabrinayusrina03/eksperimen_SML_SabrinaYusrina.mlflow
          MLFLOW_TRACKING_USERNAME: Sabrinayusrina03
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |

      - name: Run MLflow Project (Training Model)
        run: |
          mlflow run ./MLProject -P data_path=laptop_clean.csv --experiment-name "CI_Workflow_Run"
