name: Model Retraining CI

on:
  push:
    branches:
      - main

jobs:
  run-mlflow-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: 'latest'
          python-version: '3.10'
          activate-environment: true
          auto-update-conda: true
          auto-activate-base: false

      - name: Set MLflow Tracking Credentials
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/Sabrinayusrina03/eksperimen_SML_SabrinaYusrina.mlflow
          MLFLOW_TRACKING_USERNAME: Sabrinayusrina03
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |

      - name: Run MLflow Project (Training Model)
        run: |
          mlflow run ./MLProject -P data_path=MLProject/laptop_clean.csv --experiment-name "CI_Workflow_Run"
